### ISSUE TITLE
Using PProf.jl on JupyterHub

### ISSUE THREAD

**Issue by renatobellotti** [JuliaPerf/PProf.jl#80]
Hi,

I'm trying to get PProf running on a JupyterHub. Unfortunately, I cannot access the webserver that is started in the background due to firewall restrictions.

However, I can mount the remote directory on my local machine. Which commands do I have to use to visualise the allocations with pprof using the ``alloc-profile.pb.gz``?

**Comment by vchuravy** [comment]
You can use `PProf.refresh(file="...")` to open a new file in the server (and start it).

**Comment by renatobellotti** [comment]
Thanks for the quick answer! This works perfectly.
