### ISSUE TITLE
profile.pb.gz: malformed profile: found location with reserved id=0

### ISSUE THREAD

**Issue by wly2014** [JuliaPerf/PProf.jl#93]
When I run `PProf.pprof()`. I met this error:
```
profile.pb.gz: malformed profile: found location with reserved id=0
pprof: failed to fetch any source profiles
```

versioninfo:
```
Julia Version 1.9.3
Commit bed2cd540a1 (2023-08-24 14:43 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 32 × 13th Gen Intel(R) Core(TM) i9-13900K
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, goldmont)
  Threads: 1 on 32 virtual cores
```

Thanks.

**Comment by torfjelde** [comment]
Also running into the same issue. Anyone know of a workaround?

**Comment by vchuravy** [comment]
If you can get a backtrace from where the hang is coming from there might be something we can intuit from it.

**Comment by Azercoco** [comment]
I am also encountering the issue, did anyone found a solution ?

**Comment by jarbus** [comment]
Experiencing this as well

**Comment by theo-brown** [comment]
I also have this issue, but downgrading to 2.3.0 didn't fix it

**Comment by NHDaly** [comment]
Could someone who is experiencing this issue please upload the `.pb.gz` that has the problem? it should be in the CWD of wherever you are running pprof.

And cherry-on-top would be to provide a reproducible MRE that would let us demonstrate this ourselves!

**Comment by awadell1** [comment]
This reproduces the issue for me on v3.1.0:

```julia
using PProf
@pprof map(sin, rand(1000))
```

Here's the generated [`profile.pb.gz`](https://github.com/user-attachments/files/15514963/profile.pb.gz)

System information:
```
julia> versioninfo()
Julia Version 1.10.3
Commit 0b4590a5507 (2024-04-30 10:59 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 192 × AMD EPYC 9654 96-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, znver3)
Threads: 1 default, 0 interactive, 1 GC (on 192 virtual cores)
Environment:
  LD_LIBRARY_PATH = /sw/pkgs/arc/gcc/10.3.0/lib64:/sw/pkgs/arc/python/3.11.5/lib:/nfs/turbo/coe-venkvis/awadell
/mist/deepspeed/.venv/lib
  JULIA_PKG_USE_CLI_GIT = true
  LD_RUN_PATH = /sw/pkgs/arc/gcc/10.3.0/lib64
```

**Comment by hi-mel** [comment]
I solved on v3.1.0 by installing `pprof` from the instructions in https://github.com/google/pprof?tab=readme-ov-file#building-pprof.

Made sure `pprof` was in my `/usr/bin` by doing
```
sudo cp $HOME/go/bin/pprof /usr/bin
```

Then adding the binary to my path:
```
export PATH="$GOPATH/bin:$PATH"
```

Then something like:
```julia
using PProf
@pprof map(sin, rand(1000))
```
worked correctly and served the profile to localhost

**Comment by sprig** [comment]
Affected by the same issue; I stepped through the code and produced #97 which appears to fix this. Please try and lmk if this works for you!

**Comment by tanderson92** [comment]
> Affected by the same issue; I stepped through the code and produced #97 which appears to fix this. Please try and lmk if this works for you!

Thanks, this fixed the issue for me.

**Comment by rbeeli** [comment]
Any released fix for this? Having the same.

**Comment by sprig** [comment]
Until an "official" fix is released you can try using the PR branch by running `]add https://github.com/sprig/PProf.jl.git` in julia.

**Comment by vchuravy** [comment]
PProf.jl will warn now, but we still need to figure out the root cause
